# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eshan's Profile
email: eshanmushtaq@gmail.com
description: >
  A brief introduction to my profile.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Eshan Mushtaq'
bio: >
  Hello. I'm Eshan. A software developer, tech enthusiast, petrolhead and a Master's student at the University of Kaiserslautern.
author_image: "/assets/images/author.jpg"
twitter_username: eshmeister
github_username:  emushtaq

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
